name: linting, testing, building
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    services:
      chrome:
        image: selenium/standalone-chrome
        options: --shm-size=2g
        ports: 
          - 4444:4444
    strategy:
      matrix:
        node-versin: [17.x]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-versin }}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node-versin }}
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint:ts
      - name: linting scss
        run: npm run lint:scss
      - name: unit testing
        run: npm run test:unit
      - name: build storybook
        run: npm run storybook:build
      - name: sleep after storybook
        run: sleep 10
      - name: screenshot testing
        run: npm run test:ui:ci

